site_name: Outage Watch
repo_url: https://github.com/OSUKED/Outage-Watch
repo_name: OSUKED/Outage-Watch
edit_uri: edit/main/docs/

theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - header.autohide
    - navigation.tabs
    - navigation.instant
    - search.suggest
  palette:
    primary: black

extra:
  generator: false
  
plugins:
  - search
  
markdown_extensions:
  - attr_list

extra_css:
  - https://unpkg.com/leaflet@1.3.1/dist/leaflet.css
      
extra_javascript:
  - https://unpkg.com/leaflet@1.3.1/dist/leaflet.js
  - map.js
#   - https://raw.githubusercontent.com/calvinmetcalf/leaflet-ajax/master/dist/leaflet.ajax.min.js
  
nav:
  - Home: index.md
#   - User Guide:
#     - Downloading from EUMETSAT: 101_downloading.md